### ISSUE TITLE
TraceSpy white screen

### ISSUE THREAD

**Issue by Momoshikin** [smourier/TraceSpy#14]
I have downloaded and compiled the src

when i execute `\WpfTraceSpyCore\bin\Release\net5.0-windows\WpfTraceSpyCore.exe`
it keept as this forever:
![image](https://user-images.githubusercontent.com/92819425/175778747-757b2e33-6028-490b-aa4d-62c4f04b6229.png)

there's no window, and when I hover over the taskbar it shows that white screen as in the picture above.

Things I tried: install net 5.0 and also run it as admin, whats happening?
OS: Win10

**Comment by smourier** [comment]
Hi,

This is strange. I've rebuilt and tested and it works fine for me, as admin or not, on Windows 10 and 11. What you can check is if you have a "WpfSettings.config" file in %appdata%\Roaming\TraceSpy directory.

This file can get corrupted sometimes. If you have it, you can 1) close tracespy and 2) delete it and restart; Note you can rename it or copy it somewhere instead of deleting (in case it still contains interesting info you want to keep like ids, configuration, etc.)

**Comment by Momoshikin** [comment]
Deleting the file works correctly now, thank you!
