### ISSUE TITLE
VBA = 32-bit

### ISSUE THREAD

**Issue by garethhayter** [smourier/TraceSpy#4]
Hi. Do you know of a way to get the VBA code working in Excel 32-bit?

**Comment by smourier** [comment]
Hi, the code is supposed to work on 32 and 64-bit, but I don't have a 32-bit setup at hand. What doesn't work?

**Comment by garethhayter** [comment]
32 bit VBA doesn't support the LongLong type. I tried changing the relevant parameters to LongPtr, but that doesn't work either.

**Comment by smourier** [comment]
hmmm... my VBA is pretty rusty. You should be able to declare the LongLong type just like I declared the GUID, as a structure with two longs in it and changes the methods accordingly. Values don't matter, as REGHANDLE just an opaque thing, but it must be 64-bit long

**Comment by garethhayter** [comment]
Hi Simon. Thanks for the quick replies. VBA isn't my mother-tongue either! I added a new type:

Private Type LongLong
    Data1 As Long
    Data2 As Long
End Type

The compile error I then received was: 'User defined type may not be passed ByVal'. So I changed the handle parameter of EventWriteString to be ByRef, but then it crashes again.

Any more ideas?

**Comment by smourier** [comment]
The problem is not 32 vs 64bit VB/VBA, it's the due to old VB/VBA versions (lower than 7)

So, I have added a new ETWModule32.bas file that should support these VB/VBA versions (that only support 32-bit BTW). Since there is no 64-bit integer for these old versions, I've used Double (which is IEEE's double stored on 8-bit). It's a hack but since we don't need the content of this handle, it's seen as an opaque "thing" so it's ok..

**Comment by garethhayter** [comment]
Hi Simon. That works perfectly, thanks!
